# Generated by Django 4.1.2 on 2022-10-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=255)),
                ('difficulty', models.SmallIntegerField()),
                ('video_url', models.URLField()),
            ],
            options={
                'db_table': 'exercises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('difficulty', models.SmallIntegerField()),
                ('duration', models.TimeField()),
                ('exercises', models.ManyToManyField(to='Gymlog.exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gymlog.user')),
            ],
            options={
                'db_table': 'workouts',
                'managed': True,
            },
        ),
    ]
