# Generated by Django 4.1.4 on 2022-12-25 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='approve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 25, 18, 32, 8, 259926, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='workout',
            name='publication_state',
            field=models.IntegerField(default=0),
        ),
    ]
