# Generated by Django 4.1.2 on 2022-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymlog', '0003_alter_user_managers_rename_login_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
