# Generated by Django 4.1.2 on 2022-12-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gymlog', '0004_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
